AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "PartitionKey"
          AttributeType: "S"
        - AttributeName: "SortKey"
          AttributeType: "S"
        - AttributeName: "Data"
          AttributeType: "N"
      KeySchema: 
        - AttributeName: "PartitionKey"
          KeyType: "HASH"
        - AttributeName: "SortKey"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "RelationalExampleTable"
      GlobalSecondaryIndexes: 
        - IndexName: "GSI1"
          KeySchema: 
            - AttributeName: "SortKey"
              KeyType: "HASH"
            - AttributeName: "Data"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"